source:
  - vendor/assets/javascripts/underscore.js
  - vendor/assets/javascripts/backbone.js
  - app/assets/javascripts/store/spree.js
  - app/assets/javascripts/store/paginated_collection.js
  - app/assets/javascripts/store/underscore_mixins.js
  - app/assets/javascripts/store/models/product.js
  - app/assets/javascripts/store/models/variant.js
  - app/assets/javascripts/store/models/option_type.js
  - app/assets/javascripts/store/models/option_value.js
  - app/assets/javascripts/store/models/image.js
  - app/assets/javascripts/store/models/order.js
  - app/assets/javascripts/store/models/line_item.js
  - app/assets/javascripts/store/models/adjustment.js
  - app/assets/javascripts/store/models/taxonomy.js
  - app/assets/javascripts/store/models/taxon.js
  - app/assets/javascripts/store/collections/products.js
  - app/assets/javascripts/store/collections/orders.js
  - app/assets/javascripts/store/collections/line_items.js
  - app/assets/javascripts/store/collections/adjustments.js
  - app/assets/javascripts/store/collections/variants.js
  - app/assets/javascripts/store/collections/option_types.js
  - app/assets/javascripts/store/collections/option_values.js
  - app/assets/javascripts/store/collections/images.js
  - app/assets/javascripts/store/collections/taxonomies.js
  - app/assets/javascripts/store/collections/taxons.js
layout: store/templates/layouts/spree_application
